### ISSUE TITLE
The normalization after grouping seems not be applied in the source code

### ISSUE THREAD

**Issue by linwk20** [NVlabs/GroupViT#17]
Thanks for your code sharing!

![image](https://user-images.githubusercontent.com/86647905/162619357-ba0082cc-c309-44dd-b4fb-5205f30fd200.png)

Normalization Step above (copied from Group-ViT arxiv pre-print) seems not be applied in the code, is that true? And I found that the normalization  may make training unstable (not in ViT but other backbone), did you encounter the same problem?

**Comment by xvjiarui** [comment]
Hi @linwk20 
It's applied here https://github.com/NVlabs/GroupViT/blob/b4ef51b8ae997f4741811025ac2290df3423a27a/models/group_vit.py#L164

**Comment by xvjiarui** [comment]
We found that normarlization actually makes the training stable.

**Comment by linwk20** [comment]
I found it! Thanks for your reply! It seems like I have used a wrong eps value, I will try more, thanks!

**Comment by linwk20** [comment]
Maybe it is indeed caused by the wrong eps value. 
I set it as 1e-10 at first, and the training become very unstable, after changing it to 1.0, everything seems to be so good.

**Comment by linwk20** [comment]
But it still need more experiments to find why 1e-10 cause the instability, I can not explain it now...

**Comment by linwk20** [comment]
I think I know the reason. The reason is that though feed-forward is one-hot, but back propagation is through the soft value. So the small eps will enlarge the gradient to a very big value when zero-token is assign to a group, and than cause the training to be unstable or even diverge. So the default value 1.0 is actually a very good choice.
