### ISSUE TITLE
how to Train on multiple nodes

### ISSUE THREAD

**Issue by Qi-Zhangyang** [NVlabs/GroupViT#19]
The command is 
(node0)$ ./tools/dist_mn_launch.sh main_group_vit.py configs/group_vit_gcc_yfcc_30e.yml 0 2 8 tcp://node0
(node1)$ ./tools/dist_mn_launch.sh main_group_vit.py configs/group_vit_gcc_yfcc_30e.yml 1 2 8 tcp://node0
 I want to ask how can I do with the tcp://node0 ??? what is it?
Thank you very much.

**Comment by xvjiarui** [comment]
Hi @Qi-Zhangyang 

`tcp://node0` mean the IP address for the node0.

**Comment by Qi-Zhangyang** [comment]
Another question.
When I train on 8GPU on one machine.
I have noticed that only two GPUs has been used.
It is my own question?

**Comment by Qi-Zhangyang** [comment]
Another question.
When I train on 8GPU on one machine.
I have noticed that only two GPUs has been used.
It is my own question?

**Comment by xvjiarui** [comment]
Could you please paste the command you run?

**Comment by Qi-Zhangyang** [comment]
Thank you very much. I use another dataloader instead of webdataset, it works now.

**Comment by xvjiarui** [comment]
Hi @Qi-Zhangyang 
I don't think your GPU issue is related to the dataset class we use. You may need to double check it.
