### ISSUE TITLE
 Question on the text prompt

### ISSUE THREAD

**Issue by slyviacassell** [NVlabs/GroupViT#21]
The question is that how to generate so many prompt templates? Is the inspiration from other work?

> https://github.com/NVlabs/GroupViT/blob/b4ef51b8ae997f4741811025ac2290df3423a27a/datasets/imagenet_template.py#L27

**Comment by xvjiarui** [comment]
Hi @slyviacassell 
It's from OpenAI [CLIP](https://github.com/openai/CLIP/blob/main/notebooks/Prompt_Engineering_for_ImageNet.ipynb). The header file show the licensee from OpenAI.

**Comment by slyviacassell** [comment]
Oh, thank you!
