### ISSUE TITLE
Question about the mask generation

### ISSUE THREAD

**Issue by yeliudev** [NVlabs/GroupViT#26]
Hi @xvjiarui, thanks for your great work! I'm confused about how did you generate the smooth object masks based on the grouping allocation among 16 * 16 patches per image. Why the masks are not aligned with the 16 * 16 grids?

**Comment by xvjiarui** [comment]
Hi @yeliudev 

Thanks for your interest in our work.

We bilinearly resize the attention map so that the mask is more smooth.

**Comment by yeliudev** [comment]
> Hi @yeliudev
> 
> Thanks for your interest in our work.
> 
> We bilinearly resize the attention map so that the mask is more smooth.

I see. Thanks for your reply!
