### ISSUE TITLE
Background threshold.

### ISSUE THREAD

**Issue by yash0307** [NVlabs/GroupViT#31]
Many thanks for the good work. I am curious about how the background thresholds for PASCAL VOC and PASCAL context were determined?

**Comment by xvjiarui** [comment]
Hi @yash0307 
It's specified here https://github.com/NVlabs/GroupViT/blob/13b786155a1dfffe4703f40d028c92be58e1178d/segmentation/configs/_base_/datasets/pascal_voc12.py#L40, `bg_thresh`
