### ISSUE TITLE
NaN when training with GCC3M using group_vit_gcc_yfcc_30e.yml config

### ISSUE THREAD

**Issue by yxchng** [NVlabs/GroupViT#43]
NaN in loss started to appear in the 2nd epoch. Is this to be expected?

**Comment by xvjiarui** [comment]
Hi @yxchng 

Sometimes the training is not stable. May I ask what's your dataset and batch size?

**Comment by yxchng** [comment]
Dataset is GCC3M, size 2850879. (Many of the original links were broken). Batch size 4096, training on 16 A100s.

I started with GCC3M instead of GCC12M + YFCC14M because the latter is too large and I want to toy with a smaller model first.

**Comment by yxchng** [comment]
@xvjiarui Can I know what is your dataset statistics? How many images do you sucessfully download for each dataset used?

**Comment by xvjiarui** [comment]
Hi @yxchng 
The number of images I download could be found here https://github.com/xvjiarui/GroupViT/blob/dbaf9e85a6903c948df05f292d0b2091e9852f94/configs/default.yml#L11-L30
