### ISSUE TITLE
Clarification on the training datasets used.

### ISSUE THREAD

**Issue by yash0307** [NVlabs/GroupViT#46]
Hi, for the model that achieves 52.3% mIoU on PASCAL VOC, the paper says that GCC12M + YFCC14M are used for training. Whereas, in the config files of this repository GCC3M is also used. Which one is correct?

In case if GCC3M is also used, are the pre-trainings for fully supervised transfer in Table 5. done using GCC3M as well?

Thank you in advance.

**Comment by xvjiarui** [comment]
Hi @yash0307 

Sorry for the confusion. 

Yes. We are using CC3M as well.

**Comment by yash0307** [comment]
Thank for the quick reply.
