### ISSUE TITLE
Do you use "raw_caption" or "caption" as the caption in RedCaps12m?

### ISSUE THREAD

**Issue by yxchng** [NVlabs/GroupViT#47]
RedCaps12m has "raw_caption" and "caption" in its annotations. Can I know which one do you use?

**Comment by xvjiarui** [comment]
Hi @yxchng 
I use "caption". 

Please refer to conversion script for details https://github.com/NVlabs/GroupViT/blob/13b786155a1dfffe4703f40d028c92be58e1178d/convert_dataset/process_redcaps.py#L41
