### ISSUE TITLE
Confused by the visualization results

### ISSUE THREAD

**Issue by liuxingbin** [NVlabs/GroupViT#48]
Hi, Thank you for your great work.
I am confused by the visualization results. In my opinion, the final assignment is image patch (pixels in same patch have same class/group). 
The setting for training is an image resolution of 224x224 and a patch size of 16x16.
I assume there should have a clear grid effect in the final visualization.
But in your paper, visualization results have perfect curve.

Best.

**Comment by WalBouss** [comment]
Hi,
The "perfect curves" are due to the fact that during inference, they resize each input image to have a shorter side length of 448 (_i.e. each image has a minimum size of 448x448_). Also, they use bilinear interpolation with a factor _p(=patch size)_ to upsample the predictions.

**Comment by xvjiarui** [comment]
Hi @liuxingbin sorry for the late reply. 

Thanks @WalBouss for detailed answer. @WalBouss  is correct about that.
