### ISSUE TITLE
Inquiry about the Grouping Blocks

### ISSUE THREAD

**Issue by yeliudev** [NVlabs/GroupViT#54]
Hi @xvjiarui, Thanks for your great work on GroupViT!

I notice that in your implementation of the grouping blocks [here](https://github.com/NVlabs/GroupViT/blob/main/models/group_vit.py), L280-L281 and L285 are not mentioned in the paper, especially the pre-attention part.

May I ask that are these designs crucial to equip the model with grouping abilities? I've failed to reproduce your results using the information in the paper only, i.e. implementing the grouping block as simply as using a cross-attention (q: grouping tokens, kv: visual tokens) block with Gumbel Softmax and hard assignment strategy.

**Comment by xvjiarui** [comment]
Hi @yeliudev 

Thanks for your interest in our work. 

We didn't ablate the pre-attention. We have it because we would like to propagate the information  before grouping. You may have a try of our implementation.

**Comment by yeliudev** [comment]
Thanks!
