### ISSUE TITLE
How to choose the number of learnable group tokens in each stage?

### ISSUE THREAD

**Issue by InfinityBox** [NVlabs/GroupViT#8]
Hi, thank you for your great work!
I'm just wondering how to choose the number of learnable group tokens in each stage? Is it a random number at the first stage, such as 64, and then decreases as the grouping stage goes deeper?

Thank you very much!

**Comment by xvjiarui** [comment]
Hi @InfinityBox 
We experiment with different numbers(Table 2) and found 64 and 8 are sufficient for first and second stage. 
The grouping number should decrease as going deeper, in this way, we could group small segments into larger ones
